<template>
    <div class="section">
        <div class="container d-flex align-items-center px-5">
            <div class="col-50 text-container">
                <div class="d-flex align-items-center justify-content-start text-start">
                    <img src="../assets/img/ArturoArnò.jpg" alt="Arturo Arnò" class="title-img d-sm-block d-lg-none">
                    <h1>Hi,<br> I'm Arturo Arnò</h1>
                </div>
                <p class="text-start">Junior Developer, my curiosity led me to become passionate about the world of
                    coding and keeps me updated on web development, a passion generated by my past as a graphic designer
                    where, approaching web design, I wanted to discover how to create what I designed.
                </p>
                <button class="primary-btn" @click="goToContacts()">Learn more</button>
            </div>
            <div class="col-50 image-container d-none d-lg-block">
                <div class="image">
                    <img src="../assets/img/ArturoArnò.jpg" alt="Arturo Arnò">
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    methods: {
        goToContacts() {
            window.scrollTo(0, 1600);
        }
    }

}
</script>

<style scoped lang="scss">
.section {
    position: relative;
    z-index: 4;

    .container {
        .text-container {
            text-align: left;

            h1,
            p {
                padding-bottom: 1rem;
            }

            .title-img {
                max-width: 100px;
                border-radius: 1rem;
                overflow: hidden;
                box-shadow: 0.5rem 0.5rem 0 var(--blue);
            }
        }

        .image-container {
            .image {
                margin: auto;
                max-width: 300px;
                border-radius: 1rem;
                overflow: hidden;
                box-shadow: 1rem 1rem 0 var(--blue);
            }
        }
    }
}

@media screen and (max-width: 991px) {
    .col-50 {
        width: 100%;
    }

    .section {

        .container {
            padding: 1.5rem !important;

            .text-container {
                text-align: center;

                .d-flex {
                    padding-bottom: 1.5rem;

                    h1 {
                        padding-left: 1.5rem;
                        padding-bottom: 0;
                        margin-bottom: 0;
                    }
                }
            }
        }
    }
}
</style>